# Generated by Django 4.0.5 on 2022-08-22 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_board',
            fields=[
                ('E_no', models.AutoField(primary_key=True, serialize=False)),
                ('E_event_no', models.IntegerField(blank=True)),
                ('E_progress', models.CharField(max_length=20)),
                ('E_title', models.CharField(max_length=100)),
                ('E_content', models.CharField(max_length=2000)),
                ('E_start_day', models.CharField(max_length=50)),
                ('E_end_day', models.CharField(max_length=50)),
                ('E_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='R_board',
            fields=[
                ('R_no', models.AutoField(primary_key=True, serialize=False)),
                ('R_e_no', models.IntegerField()),
                ('R_writer', models.CharField(max_length=100)),
                ('R_content', models.CharField(max_length=1000)),
                ('R_createdate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 22, 18, 54, 58, 101114))),
            ],
        ),
    ]
