# Generated by Django 4.0.5 on 2022-08-24 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_e_board_e_image02_alter_r_board_r_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_board',
            name='R_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 24, 16, 30, 52, 952931)),
        ),
    ]
