# Generated by Django 4.0.5 on 2022-08-31 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_r_board_r_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_board',
            name='R_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 1, 8, 45, 46, 180098)),
        ),
    ]
