# Generated by Django 4.0.5 on 2022-08-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_no', models.IntegerField(blank=True)),
                ('M_title', models.CharField(max_length=100)),
                ('M_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
