# Generated by Django 4.0.5 on 2022-08-31 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='f_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 1, 8, 44, 16, 899611)),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='f_updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 1, 8, 44, 16, 899621)),
        ),
        migrations.AlterField(
            model_name='lboard',
            name='L_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 1, 8, 44, 16, 899796)),
        ),
        migrations.AlterField(
            model_name='lboard',
            name='L_updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 1, 8, 44, 16, 899803)),
        ),
    ]
